### ISSUE TITLE
Add Saritasa.Upsource module

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/PSGallery#46]
Create new Saritasa.Upsource project in Saritasa.PSGallery.sln (https://github.com/Saritasa/PSGallery/tree/develop/src).

It should export 2 cmdlets:

Initialize-Upsource
- [string] UpsourceUrl
- [PSCredential] Credential

Returns nothing.

Get-RevisionsWithoutReview
- [string] Project
- [string] Branch = 'develop'
- [int] DaysLimit = 30

Returns array of objects with properties:
- [string] Revision
- [date] Date
- [string] Author
- [string] CommitMessage

Add Saritasa.Upsource module definition to https://github.com/Saritasa/PSGallery/tree/develop/modules similar to Saritasa.Git.

Copy new DLL in https://github.com/Saritasa/PSGallery/blob/develop/default.ps1 (build task).

----

Examples:

Initialize-Upsource -UpsourceUrl 'https://upsource.example.com/' -Credential (Get-Credential 'JohnDoe')
Get-RevisionsWithoutReview -Project 'crm'
Get-RevisionsWithoutReview -Project 'crm' -Branch 'master'
Get-RevisionsWithoutReview -Project 'crm' -Branch 'master' -DaysLimit 7

----

1. Get last revisions.

POST https://upsource.example.com/~rpc/getRevisionsList
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

{"projectId":"crm", "limit":30, "query":"branch: develop"}

2. Get revision info. Ignore, if it's merge.

POST https://upsource.example.com/~rpc/getRevisionInfo
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

{"projectId":"crm", "revisionId":"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"}

3. Get review info.

POST https://upsource.example.com/~rpc/getRevisionReviewInfo
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

{"projectId":"crm", "revisionId":"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"}

If reviewInfo array is empty, add the revision to results.

----

In next iteration of the cmdlet, we may cache some results in local SQLite database.

**Comment by Artur2** [comment]
@dermeister0  fixed with #48
