### ISSUE TITLE
Invoke-XunitRunner does not work with version 2.3.1

### ISSUE THREAD

**Issue by dermeister0** [Saritasa/PSGallery#88]
> Exception: The term 'C:\Temp\src\packages\xunit.runner.console.2.3.1\.\tools\xunit.console.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

```
    Directory: C:\Temp\xunit.runner.console.2.3.1\tools


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/6/2018   5:15 PM                net452
d-----         3/6/2018   5:15 PM                netcoreapp1.0
d-----         3/6/2018   5:15 PM                netcoreapp2.0
```

Need to add `net452` to command:

```
$xunitExe = Join-Path $xunitExeDirectory.FullName '.\tools\net452\xunit.console.exe'
```

**Comment by krasninja** [comment]
Fix https://github.com/Saritasa/PSGallery/tree/feature/xunit-runner-fix
